name: Java CI with Gradle

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:

    runs-on: MacOS-Latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: Library-Backend
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: Library-Backend
      - name: Deploy to Heroku
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: 603f6273-45f6-4eec-b6b0-b41604e7d648
          heroku_app_name: "library-backend-a6a" #Must be unique in Heroku
          heroku_email: "mohamed.benkirane@mail.mcgill.ca"
          buildpack: "https://github.com/HashNuke/heroku-buildpack-elixir.git"
      
        
